// <auto-generated />
using System;
using Clinica.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinica.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20260814015119_EstornoDeCobranca")]
    partial class EstornoDeCobranca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinica.Domain.Anamnesis.AnamnesisLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_anamnesis_links");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_anamnesis_links_token");

                    b.ToTable("anamnesis_links", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Anamnesis.AnamnesisResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DataConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("data_consent");

                    b.Property<bool>("ImageConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("image_consent");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_anamnesis_responses");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_anamnesis_responses_patient_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_anamnesis_responses_tenant_id");

                    b.HasIndex("TenantId", "PatientId")
                        .HasDatabaseName("ix_anamnesis_responses_tenant_id_patient_id");

                    b.ToTable("anamnesis_responses", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("ExecutionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("execution_notes");

                    b.Property<DateTimeOffset?>("FollowUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_at");

                    b.Property<DateTimeOffset?>("FollowUpSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_sent_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("ProcedureId")
                        .HasDatabaseName("ix_appointments_procedure_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_appointments_professional_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_appointments_tenant_id");

                    b.HasIndex("TenantId", "FollowUpAt")
                        .HasDatabaseName("ix_appointments_tenant_id_follow_up_at");

                    b.HasIndex("TenantId", "PatientId")
                        .HasDatabaseName("ix_appointments_tenant_id_patient_id");

                    b.HasIndex("TenantId", "StartsAt")
                        .HasDatabaseName("ix_appointments_tenant_id_starts_at");

                    b.HasIndex("TenantId", "ProfessionalId", "StartsAt")
                        .HasDatabaseName("ix_appointments_tenant_id_professional_id_starts_at");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_e164");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_patients_tenant_id");

                    b.HasIndex("TenantId", "PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_tenant_id_phone_e164");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int?>("InstallmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("installment_count");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("installment_number");

                    b.Property<string>("Method")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TreatmentPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("treatment_plan_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_payments_appointment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payments_tenant_id");

                    b.HasIndex("TenantId", "AppointmentId")
                        .HasDatabaseName("ix_payments_tenant_id_appointment_id");

                    b.HasIndex("TenantId", "Status", "DueDate")
                        .HasDatabaseName("ix_payments_tenant_id_status_due_date");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Procedures.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("SuppliesCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("supplies_cost");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_procedures");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_procedures_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_procedures_tenant_id_name");

                    b.ToTable("procedures", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Professionals.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("KeycloakUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_user_id");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_professionals");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_professionals_tenant_id");

                    b.HasIndex("TenantId", "Active")
                        .HasDatabaseName("ix_professionals_tenant_id_active");

                    b.ToTable("professionals", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Professionals.ScheduleException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("BreakEndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_ends_at");

                    b.Property<TimeOnly?>("BreakStartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_starts_at");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_schedule_exceptions");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_schedule_exceptions_professional_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schedule_exceptions_tenant_id");

                    b.HasIndex("TenantId", "ProfessionalId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_exceptions_tenant_id_professional_id_date");

                    b.ToTable("schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Professionals.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("BreakEndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_ends_at");

                    b.Property<TimeOnly?>("BreakStartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_starts_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_schedules");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_work_schedules_professional_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_schedules_tenant_id");

                    b.HasIndex("TenantId", "ProfessionalId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_work_schedules_tenant_id_professional_id_day_of_week");

                    b.ToTable("work_schedules", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Stock.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("ContentPerUnit")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("content_per_unit");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("MinimumQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("minimum_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purchase_unit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_items_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_items_tenant_id_name");

                    b.ToTable("stock_items", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Stock.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_stock_movements_appointment_id");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_stock_movements_stock_item_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_movements_tenant_id");

                    b.HasIndex("TenantId", "StockItemId")
                        .HasDatabaseName("ix_stock_movements_tenant_id_stock_item_id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Treatments.PlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer")
                        .HasColumnName("sessions");

                    b.Property<int>("StartAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("start_after_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TreatmentPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("treatment_plan_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plan_items");

                    b.HasIndex("ProcedureId")
                        .HasDatabaseName("ix_plan_items_procedure_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_plan_items_tenant_id");

                    b.HasIndex("TreatmentPlanId")
                        .HasDatabaseName("ix_plan_items_treatment_plan_id");

                    b.HasIndex("TenantId", "TreatmentPlanId")
                        .HasDatabaseName("ix_plan_items_tenant_id_treatment_plan_id");

                    b.ToTable("plan_items", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Treatments.TreatmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginAppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_appointment_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treatment_plans");

                    b.HasIndex("OriginAppointmentId")
                        .HasDatabaseName("ix_treatment_plans_origin_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_treatment_plans_patient_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_treatment_plans_professional_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_treatment_plans_tenant_id");

                    b.HasIndex("TenantId", "PatientId", "Status")
                        .HasDatabaseName("ix_treatment_plans_tenant_id_patient_id_status");

                    b.ToTable("treatment_plans", (string)null);
                });

            modelBuilder.Entity("Clinica.Domain.Anamnesis.AnamnesisResponse", b =>
                {
                    b.HasOne("Clinica.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anamnesis_responses_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinica.Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("Clinica.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.HasOne("Clinica.Domain.Procedures.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_procedures_procedure_id");

                    b.HasOne("Clinica.Domain.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_professionals_professional_id");

                    b.Navigation("Patient");

                    b.Navigation("Procedure");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Clinica.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Clinica.Domain.Appointments.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinica.Domain.Professionals.ScheduleException", b =>
                {
                    b.HasOne("Clinica.Domain.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_exceptions_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Clinica.Domain.Professionals.WorkSchedule", b =>
                {
                    b.HasOne("Clinica.Domain.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_schedules_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Clinica.Domain.Stock.StockMovement", b =>
                {
                    b.HasOne("Clinica.Domain.Appointments.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_movements_appointments_appointment_id");

                    b.HasOne("Clinica.Domain.Stock.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_stock_items_stock_item_id");

                    b.Navigation("Appointment");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Clinica.Domain.Treatments.PlanItem", b =>
                {
                    b.HasOne("Clinica.Domain.Procedures.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_items_procedures_procedure_id");

                    b.HasOne("Clinica.Domain.Treatments.TreatmentPlan", "TreatmentPlan")
                        .WithMany("Items")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_items_treatment_plans_treatment_plan_id");

                    b.Navigation("Procedure");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("Clinica.Domain.Treatments.TreatmentPlan", b =>
                {
                    b.HasOne("Clinica.Domain.Appointments.Appointment", "OriginAppointment")
                        .WithMany()
                        .HasForeignKey("OriginAppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_treatment_plans_appointments_origin_appointment_id");

                    b.HasOne("Clinica.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treatment_plans_patients_patient_id");

                    b.HasOne("Clinica.Domain.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treatment_plans_professionals_professional_id");

                    b.Navigation("OriginAppointment");

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Clinica.Domain.Treatments.TreatmentPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
